### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Yoshimi0824** [Yoshimi0824/furima_31718#9]
#URL
https://furima-31718.herokuapp.com/

#Basic認証のIDとパスワード
 ID: admin
 パスワード: 2222

#出品者用のメールアドレスとパスワード
 email: sample@sample
 パスワード: s174571

#購入者用のメールアドレスとパスワード
 email: test@test
 パスワード: s174571

#購入用カードの番号・期限・セキュリティコード
 番号: 4242424242424242
 期限: 3/23
 コード: 123

ご確認の程、よろしくお願い致します。

**Comment by mo1015** [comment]
阿部さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

**※補足　記載の購入者用アカウントでログインができませんでした。最終課題説明文にはログインできるアカウントの記載をしましょう！**
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
